apiVersion: apps/v1
kind: Deployment
metadata:
  name: site1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site1
  template:
    metadata:
      labels:
        app: site1
    spec:
      containers:
      - name: site1
        image: nginx:alpine
        volumeMounts:
        - name: site1-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site1-html
        configMap:
          name: site1-html
---
apiVersion: v1
kind: Service
metadata:
  name: site1-service
spec:
  type: NodePort
  selector:
    app: site1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001