apiVersion: apps/v1
kind: Deployment
metadata:
  name: site2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site2
  template:
    metadata:
      labels:
        app: site2
    spec:
      containers:
      - name: site2
        image: nginx:alpine
        volumeMounts:
        - name: site2-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site2-html
        configMap:
          name: site2-html
---
apiVersion: v1
kind: Service
metadata:
  name: site2-service
spec:
  type: NodePort
  selector:
    app: site2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002